### ISSUE TITLE
Post order into Prestashop back office throughout web service

### ISSUE THREAD

**Issue by ghost** [SKaDiZZ/angular2-presta#2]
Hi,

I already implement to display my product information into my ionic application throughout Prestashop web service by using Get method. 
eg. 
```
this.http.get("http://www.example.com/api/products/?ws_key=xxxxxxxx&output_format=JSON&display=full").map(res => res.json()).subscribe(data => {
});
```
I also implement that new customer could sign up in the app, and customer data will be upload throughout Prestashop Web service. People who manage the back office could look at that a new customer sign up. I know that the default data for Prestashop is XML so I upload XML data back to its API.
eg.
```
//I only upload the data that Prestashop requires according to errors by testing, but I do not know //what data exactly Prestashop needs.
//I upload address without customer id, which makes address not display in the back office.
let customer = "<prestashop><customer><firstname>"+  this.newUser.first_name +"</firstname><lastname>" + this.newUser.last_name + "</lastname><email>" + this.newUser.email + "</email><passwd>" + this.newUser.password + "</passwd><active>1</active><newsletter>1</newsletter></customer></prestashop>" ;
let linkToCustomer = 'http://www.example.com/api/customers/?ws_key='+ this.apikey + '&output_format=JSON&display=full';
this.http.post(linkToCustomer, customer, {headers: headers}).map(res => res.json()).subscribe(data => {
});
```
The last step for me is to upload order after customers purchase. This step is quite difficult since each order interacts with several api pages such as api/orders, api/carriers, api/carts, api/orders_invoice and so on. I want to data could display on back office just like customers make an order through web broswer, and sales representatives could manage orders on back office.

Could you please give some suggestion about my problem.
Look forward to receiving your reply soon.
Cheers,

Yifei

**Comment by SKaDiZZ** [comment]
This question isn't angular2-presta library related. So it isn't issue with my library. I still didn't found good and reliable way of posting xml documents required by presta webservice. Please if you have any questions unrelated to this library you can ask them over Telegram app channel virtuooza.
