### ISSUE TITLE
Need to import HttpModule

### ISSUE THREAD

**Issue by psegarel** [SKaDiZZ/angular2-presta#3]
node v7.7.2
angular 4.2.4
@angular/cli 1.3.2

// The following triggered the error 'No provider for Http' 
constructor(private _prestaService: PrestaService) {}

Solved by adding the HttpModule
https://stackoverflow.com/questions/33721276/angular-2-no-provider-for-http

**Comment by SKaDiZZ** [comment]
You have to import HttpClientModule in your app.module.ts and in imports because library is considering it as third party dependency.
