### ISSUE TITLE
How access to the category name of a specifique product

### ISSUE THREAD

**Issue by moraoscar** [SKaDiZZ/angular2-presta#6]
How to access the category of a specific product?
I am looking for the list of active products, and at the time of showing it I would like to show: name, price and to which category the product belongs, but this last thing is not clear to me how I can do it.

I know this is not an error as such, but I would appreciate your comment.

**Comment by SKaDiZZ** [comment]
When you get product or list of products from API you will also get list of catergory id's in response.

```json
"associations": {
"categories": [
{
"id": "2"
},
{
"id": "3"
},
{
"id": "4"
},
{
"id": "5"
}
],
```
Now you can get one by one category by using those id's then you will have name.
```typescript
query: Angular2PrestaQuery = {
    resource: 'categories',
    filter: {
      id: '2'
    }
  };
```
There are many different ways to do it I guess. You could also fetch all categories at once and then make pipe which would automatically match id of current product with category.

To get all categories from shop:
```typescript
query: Angular2PrestaQuery = {
    resource: 'categories'
  };
 this.categories$ = this._service.get(this.query);
```
You should also check webservice documentation I provided links in readme.

**Comment by SKaDiZZ** [comment]
Please read documentation carefully there are examples for all of those things you want to do.
