### ISSUE TITLE
Enable Prestashop for CORS petitions using `.htaccess`

### ISSUE THREAD

**Issue by amoncusir** [SKaDiZZ/angular2-presta#8]
Hi!

I send this issue for show how enable CORS without modify Prestashop code using a `.htaccess` file. In this way only works with Apache HTTP server and miss configurations for others HTTP servers, like Nginx.

My prupose is for add this script in the main `README` and help other users when working with SPA and need enable CORS.

Thank's for your project!

PD. Sorry for mi english!
```
<IfModule mod_headers.c>
   Header always set Access-Control-Allow-Origin "*"
   Header always set Access-Control-Allow-Headers "Content-Type, Authorization, Io-Format, Accept"
   Header always set Access-Control-Allow-Methods "GET,POST,HEAD,DELETE,PUT,OPTIONS"
</IfModule>

<IfModule mod_rewrite.c>
  # Added a rewrite to respond with a 200 SUCCESS on every OPTIONS request
  RewriteEngine On
  RewriteCond %{REQUEST_METHOD} OPTIONS
  RewriteRule ^(.*)$ $1 [R=200,L]
</IfModule>
```

**Comment by SKaDiZZ** [comment]
Thank you for your contribution I'll add your example into readme file.

**Comment by amoncusir** [comment]
You're welcome! Only one thing, this example is for Apache, not Nginx! 😆

**Comment by SKaDiZZ** [comment]
ill update it thnx
